services:
  backend:
    build:
      context: ./Backend/Backend
      dockerfile: Dockerfile
    env_file:
      - ./Backend/Backend/.env
    ports:
      - "5000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
    - ./Backend/Backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    image: nginx
    build: ./Frontend/front
    ports:
      - "4200:80"
volumes:
  pgdata: