name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  backend-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: Backend/TestProject1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0
      - run: dotnet restore
      - run: dotnet build --no-restore

  backend-tests:
    runs-on: ubuntu-latest
    needs: backend-build

    defaults:
      run:
        working-directory: Backend/TestProject1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0

      - run: dotnet test 

  frontend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend/front

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Frontend/front/package-lock.json

      - run: npm ci
      - run: npm run build

  frontend-tests:
    runs-on: ubuntu-latest
    needs: frontend-build

    defaults:
      run:
        working-directory: Frontend/front

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: Frontend/front/package-lock.json

      - run: npm ci
      - run: npm test -- --watch=false --browsers=ChromeHeadless